# Fandoms Analysis

In [7]:
import pandas as pd

df = pd.read_csv('ships_complete.csv', encoding='latin1')
df.head()

,year,rank,name,character 1,character 2,show,pairs,canon,rpf
0,2013,1,MakoHaru,Nanase Haruka,Tachibana Makoto,Free!,M/M,No,No
1,2013,2,J2,Jared Padalecki,Jensen Ackles,actors,M/M,No,Yes
2,2013,3,Larry Stylinson,Harry Styles,Louis Tomlinson,One Direction,M/M,No,Yes
3,2013,4,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
4,2013,5,Johnlock,John Watson,Sherlock,Sherlock,M/M,No,No

## highrankers (#1 ship from each year)

In [30]:
# groupby creates two groups, where rank 1 is either True or False
# get_group only retrieves the True group, then we obtain the names

rank_1 = df.groupby(df['rank']==1).get_group(True)['name']

# turn it into a list
rank_1_list = [name for name in rank_1]
rank_1_list

['MakoHaru',
 'Destiel',
 'Larry Stylinson',
 'Clexa',
 'Klance',
 'Klance',
 'Ineffable Husbands',
 'Reylo',
 'Destiel',
 'Byler']

In [39]:
# create a dataframe named rank_1_df and populate it with just the rank 1 ships
# use set() to keep unique names and pd.concat to keep adding to the dataframe
# reset the index

rank_1_df = pd.DataFrame()

for name in set(rank_1_list):
    rank_1_df = pd.concat([rank_1_df, df[df['name'] == name]])

rank_1_df = rank_1_df.reset_index(drop=True)

rank_1_df

,year,rank,name,character 1,character 2,show,pairs,canon,rpf
0,2022,1,Byler,Will Byers,Mike Wheeler,Stranger Things,M/M,No,No
1,2013,1,MakoHaru,Nanase Haruka,Tachibana Makoto,Free!,M/M,No,No
2,2014,8,MakoHaru,Makoto Tachibana,Haruka Nanase,Free!,M/M,No,No
3,2013,4,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
4,2014,1,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
5,2015,3,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
6,2016,4,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
7,2017,11,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
8,2018,11,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
9,2019,20,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
10,2020,10,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
11,2021,1,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
12,2022,3,Destiel,Dean Winchester,Castiel,Supernatural,M/M,Yes,No
13,2019,1,Ineffable Husbands,Aziraphale,Crowley,Good Omens,M/M,No,No
14,2020,5,Ineffable Husbands,Aziraphale,Crowley,Good Omens,M/M,No,No
15,2022,18,Ineffable Husbands,Aziraphale,Crowley,Good Omens,M/M,No,No
16,2015,8,Clexa,Clarke Griffin,Commander Lexa,The 100,F/F,Yes,No
17,2016,1,Clexa,Clarke Griffin,Commander Lexa,The 100,F/F,Yes,No
18,2016,10,Reylo,Rey,Kylo Ren,the Star Wars universe,F/M,Yes,No
19,2017,19,Reylo,Rey,Kylo Ren,the Star Wars universe,F/M,Yes,No
20,2018,2,Reylo,Rey,Kylo Ren,the Star Wars universe,F/M,Yes,No
21,2019,7,Reylo,Rey,Kylo Ren,the Star Wars universe,F/M,Yes,No
22,2020,1,Reylo,Rey,Kylo Ren,the Star Wars universe,F/M,Yes,No
23,2013,3,Larry Stylinson,Harry Styles,Louis Tomlinson,One Direction,M/M,No,Yes
24,2014,3,Larry Stylinson,Harry Styles,Louis Tomlinson,One Direction,M/M,No,Yes
25,2015,1,Larry Stylinson,Harry Styles,Louis Tomlinson,One Direction,M/M,No,Yes
26,2016,3,Larry Stylinson,Harry Styles,Louis Tomlinson,One Direction,M/M,No,Yes
27,2016,6,Klance,Keith,Lance,Voltron: Legendary Defender,M/M,No,No
28,2017,1,Klance,Keith Kogane,Lance McClain,Voltron: Legendary Defender,M/M,No,No
29,2018,1,Klance,Keith Kogane,Lance McClain,Voltron: Legendary Defender,M/M,No,No
30,2019,2,Klance,Keith Kogane,Lance McClain,Voltron: Legendary Defender,M/M,No,No
31,2020,20,Klance,Keith,Lance,Voltron: Legendary Defender,M/M,No,No

In [40]:
rank_1_df.to_csv('rank_1.csv', index=False, encoding='latin1')